language: ruby
sudo: false
cache: bundler
services:
  - redis-server
rvm:
- 2.2.0
gemfile:
  - Gemfile
script: bundle exec rake
deploy:
  provider: heroku
    app:
    master: an-deployment-test
    production: an-deployment-test
  on:
    repo: AssistNetwork/an-deployment-test
bundler_args: --without development production
